teams = [
    {"seed": 1,"name": "Furia", "img":"https://majors.im/images/rio2022_rmr/am/furi.png"},
    {"seed": 2,"name": "Liquid", "img":"https://majors.im/images/rio2022_rmr/am/liqu.png"},
    {"seed": 3,"name": "BESTIA", "img":"https://majors.im/images/paris2023_qual/best.png"},
    {"seed": 4,"name": "Complexy", "img":"https://majors.im/images/paris2023_qual/col.png"},
    {"seed": 5,"name": "Imperial", "img":"https://majors.im/images/paris2023_qual/impe.png"},
    {"seed": 6,"name": "paiN", "img":"https://majors.im/images/paris2023_qual/pain.png"},
    {"seed": 7,"name": "Fluxo", "img":"https://majors.im/images/paris2023_qual/flux.png"},
    {"seed": 8,"name": "MIBR", "img":"https://majors.im/images/paris2023_qual/mibr.png"},
    {"seed": 9,"name": "Flamengo", "img":"https://majors.im/images/paris2023_qual/flam.png"},
    {"seed": 10,"name": "yur", "img":"https://majors.im/images/paris2023_qual/yur.png"},
    {"seed": 11,"name": "Paquetá", "img":"https://majors.im/images/paris2023_qual/paqu.png"},
    {"seed": 12,"name": "Detonate", "img":"https://majors.im/images/paris2023_qual/dtn.png"},
    {"seed": 13,"name": "Fuscão", "img":"https://majors.im/images/paris2023_qual/fusc.png"},
    {"seed": 14,"name": "Nouns", "img":"https://majors.im/images/paris2023_qual/noun.png"},
    {"seed": 15,"name": "OONation", "img":"https://majors.im/images/paris2023_qual/00.png"},
    {"seed": 16,"name": "TeamOne", "img":"https://majors.im/images/paris2023_qual/los.png"},

    {"seed": 101,"name": "Virtus.pro", "img":"https://majors.im/images/paris2023_rmr/vp.png"},
    {"seed": 102,"name": "MOUZ", "img":"https://majors.im/images/paris2023_rmr/mouz.png"},
    {"seed": 103,"name": "Fnatic", "img":"https://majors.im/images/paris2023_rmr/fnat.png"},
    {"seed": 104,"name": "Natus Vincere", "img":"https://majors.im/images/paris2023_rmr/navi.png"},
    {"seed": 105,"name": "Bad News Eagles", "img":"https://majors.im/images/paris2023_rmr/bne.png"},
    {"seed": 106,"name": "Sprout", "img":"https://majors.im/images/paris2023_rmr/spro.png"},
    {"seed": 107,"name": "FaZe Clan", "img":"https://majors.im/images/paris2023_rmr/faze.png"},
    {"seed": 108,"name": "Apeks", "img":"https://majors.im/images/paris2023_rmr/apek.png"},
    {"seed": 109,"name": "GamerLegion", "img":"https://majors.im/images/paris2023_rmr/gl.png"},
    {"seed": 110,"name": "OG", "img":"https://majors.im/images/paris2023_rmr/og.png"},
    {"seed": 111,"name": "Team Falcons", "img":"https://majors.im/images/paris2023_rmr/falc.png"},
    {"seed": 112,"name": "1win", "img":"https://majors.im/images/paris2023_rmr/1win.png"},
    {"seed": 113,"name": "Into The Breach", "img":"https://majors.im/images/paris2023_rmr/itb.png"},
    {"seed": 114,"name": "Viperio", "img":"https://majors.im/images/paris2023_rmr/vipe.png"},
    {"seed": 115,"name": "B8", "img":"https://majors.im/images/paris2023_rmr/b8.png"},
    {"seed": 116,"name": "SAW", "img":"https://majors.im/images/paris2023_rmr/saw.png"},

    {"seed": 201,"name": "Heroic", "img":"https://majors.im/images/paris2023_rmr/hero.png"},
    {"seed": 202,"name": "Cloud9", "img":"https://majors.im/images/paris2023_rmr/c9.png"},
    {"seed": 203,"name": "Team Spirit", "img":"https://majors.im/images/paris2023_rmr/spir.png"},
    {"seed": 204,"name": "BIG", "img":"https://majors.im/images/paris2023_rmr/big.png"},
    {"seed": 205,"name": "ENCE", "img":"https://majors.im/images/paris2023_rmr/ence.png"},
    {"seed": 206,"name": "Team Vitality", "img":"https://majors.im/images/paris2023_rmr/vita.png"},
    {"seed": 207,"name": "Ninjas in Pyjamas", "img":"https://majors.im/images/paris2023_rmr/nip.png"},
    {"seed": 208,"name": "9INE", "img":"https://majors.im/images/paris2023_rmr/9ine.png"},
    {"seed": 209,"name": "G2 Esports", "img":"https://majors.im/images/paris2023_rmr/g2.png"},
    {"seed": 210,"name": "Eternal Fire", "img":"https://majors.im/images/paris2023_rmr/ef.png"},
    {"seed": 211,"name": "Astralis", "img":"https://majors.im/images/paris2023_rmr/astr.png"},
    {"seed": 212,"name": "Monte", "img":"https://majors.im/images/paris2023_rmr/mont.png"},
    {"seed": 213,"name": "iNation", "img":"https://majors.im/images/paris2023_rmr/inat.png"},
    {"seed": 214,"name": "Aurora Gaming", "img":"https://majors.im/images/paris2023_rmr/auro.png"},
    {"seed": 215,"name": "forZe", "img":"https://majors.im/images/paris2023_rmr/forz.png"},
    {"seed": 216,"name": "500", "img":"https://majors.im/images/paris2023_rmr/500.png"},
]